version: '3'

services:
  todofront:
    build: ./todo-app/front-end
    restart: always
    depends_on:
      - todoback
    environment:
      REACT_APP_API_HOST: todoback
      REACT_APP_API_PORT: 3001
    
  todoback:
    build: ./todo-app/back-end
    restart: always

  todotests:
    build: ./todo-app/tests
    depends_on:
      - todofront
    environment:
      FRONT_HOST: todofront
      FRONT_PORT: 3000
